# Generated by Django 5.0.1 on 2024-01-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("FirstName", models.CharField(max_length=250)),
                ("LastName", models.CharField(max_length=250)),
                ("FullName", models.CharField(max_length=250)),
                (
                    "EmployeeID",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                (
                    "DepartmentName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debt.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("FirstName", models.CharField(max_length=250)),
                ("LastName", models.CharField(max_length=250)),
                ("FullName", models.CharField(max_length=250)),
                (
                    "CustomerNationalID",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("Resident", models.CharField(max_length=250)),
                ("PhoneNumber", models.CharField(max_length=250)),
                ("Passport", models.ImageField(upload_to="Passports/")),
                ("Document", models.FileField(upload_to="Documents/")),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="debt.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LoanID", models.CharField(max_length=250)),
                ("loanStatus", models.CharField(default="Active", max_length=250)),
                ("RequestedAmount", models.FloatField()),
                ("QualityAssurance", models.FloatField(default=0.02, editable=False)),
                ("Insurance", models.FloatField(default=0.03, editable=False)),
                ("Duration", models.IntegerField()),
                ("Interest", models.FloatField(default=0.01, editable=False)),
                ("ActualDebt", models.IntegerField(editable=False)),
                ("CashReceivable", models.IntegerField(editable=False)),
                (
                    "MonthlyInstallment",
                    models.IntegerField(default=0.06, editable=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="debt.customer"
                    ),
                ),
                (
                    "EmployeeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="debt.employee"
                    ),
                ),
            ],
        ),
    ]
