# Generated by Django 5.0.1 on 2024-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0002_employee_customer_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="Duration",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="Interest",
            field=models.FloatField(default=0.1, editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="MonthlyInstallment",
            field=models.IntegerField(default=0.15, editable=False),
        ),
    ]
