# Generated by Django 5.0.1 on 2024-01-14 20:12

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0005_remove_loan_requestedamount_currency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="Interest_currency",
            new_name="QualityAssurance_currency",
        ),
        migrations.AlterField(
            model_name="loan",
            name="Interest",
            field=models.FloatField(default=0.1, editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="QualityAssurance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="TZS", max_digits=10
            ),
        ),
    ]
