# Generated by Django 5.0.1 on 2024-01-14 20:14

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "debt",
            "0006_rename_interest_currency_loan_qualityassurance_currency_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="QualityAssurance_currency",
            new_name="RequestedAmount_currency",
        ),
        migrations.AlterField(
            model_name="loan",
            name="QualityAssurance",
            field=models.FloatField(default=0.02, editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="RequestedAmount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="TZS", max_digits=10
            ),
        ),
    ]
