# Generated by Django 5.0.1 on 2024-01-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "debt",
            "0007_rename_qualityassurance_currency_loan_requestedamount_currency_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="ActualDebt_currency",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="CashReceivable_currency",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="MonthlyInstallment_currency",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="RequestedAmount_currency",
        ),
        migrations.AlterField(
            model_name="loan",
            name="ActualDebt",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="CashReceivable",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="MonthlyInstallment",
            field=models.IntegerField(default=0.15, editable=False),
        ),
        migrations.AlterField(
            model_name="loan",
            name="RequestedAmount",
            field=models.FloatField(),
        ),
    ]
