# Generated by Django 4.2.9 on 2024-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0008_remove_loan_actualdebt_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyWeatherByCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("boston_temp", models.DecimalField(decimal_places=1, max_digits=5)),
                ("houston_temp", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
