# Generated by Django 4.2.9 on 2024-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0011_customer_addedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loanStatus",
            field=models.CharField(default="Active", editable=False, max_length=250),
        ),
    ]
