# Generated by Django 4.2.9 on 2024-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0012_alter_loan_loanstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="AddedBy",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="EmployeeID",
        ),
    ]
