# Generated by Django 4.2.9 on 2024-01-19 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0014_remove_customer_document_remove_customer_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="Passport",
            field=models.ImageField(
                default=datetime.datetime(
                    2024, 1, 19, 19, 40, 56, 655358, tzinfo=datetime.timezone.utc
                ),
                upload_to="Passports/",
            ),
            preserve_default=False,
        ),
    ]
