# Generated by Django 4.2.9 on 2024-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0016_remove_customer_passport_customer_businesstype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="DateOfBirth",
            field=models.DateTimeField(),
        ),
    ]
