# Generated by Django 4.2.9 on 2024-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0017_alter_customer_dateofbirth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Amount", models.FloatField()),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
