# Generated by Django 4.2.9 on 2024-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0021_customer_nationalid_customer_passportsize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="NationalID",
            field=models.ImageField(upload_to="Documents/"),
        ),
    ]
