# Generated by Django 4.2.9 on 2024-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0024_remove_customer_status_loan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loanStatus",
            field=models.CharField(default="Active", max_length=250),
        ),
    ]
