# Generated by Django 4.2.9 on 2024-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0025_alter_loan_status_alter_loan_loanstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loanStatus",
            field=models.CharField(
                choices=[("Active", "Active"), ("Not Active", "Not Active")],
                default="Active",
                max_length=50,
                null=True,
            ),
        ),
    ]
