# Generated by Django 4.2.9 on 2024-01-21 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0027_remove_customer_nationalid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="NationalID",
            field=models.ImageField(
                default=datetime.datetime(
                    2024, 1, 21, 18, 10, 34, 697511, tzinfo=datetime.timezone.utc
                ),
                upload_to="Documents/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="PassportSize",
            field=models.ImageField(
                default=datetime.datetime(
                    2024, 1, 21, 18, 10, 44, 770021, tzinfo=datetime.timezone.utc
                ),
                upload_to="Passports/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loan",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
