# Generated by Django 4.2.9 on 2024-01-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debt", "0030_remove_target_amount_currency_alter_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
